# Change baseurl before deploy
baseurl = "https://raffwh.github.io"
languageCode = "en-us"
title = "Rafael Widjajahakim - Sample Works"

# Theme i18n support
defaultContentLanguage = "en"


hasCJKLanguage = false

# Change it to your Disqus shortname before using
#disqusShortname = "hugo-theme-stack"
enabled = false
provider = ""


[social]
github = "raffwh.github.com"
linkedin = "linkedin.com/in/rafaelwidjajahakim"



[pagination]
pagerSize = 5
